// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: geecache.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Testreq       string                 `protobuf:"bytes,1,opt,name=testreq,proto3" json:"testreq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestRequest) Reset() {
	*x = TestRequest{}
	mi := &file_geecache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRequest) ProtoMessage() {}

func (x *TestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geecache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRequest.ProtoReflect.Descriptor instead.
func (*TestRequest) Descriptor() ([]byte, []int) {
	return file_geecache_proto_rawDescGZIP(), []int{0}
}

func (x *TestRequest) GetTestreq() string {
	if x != nil {
		return x.Testreq
	}
	return ""
}

type TestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Testrsp       string                 `protobuf:"bytes,1,opt,name=testrsp,proto3" json:"testrsp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestResponse) Reset() {
	*x = TestResponse{}
	mi := &file_geecache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResponse) ProtoMessage() {}

func (x *TestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geecache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResponse.ProtoReflect.Descriptor instead.
func (*TestResponse) Descriptor() ([]byte, []int) {
	return file_geecache_proto_rawDescGZIP(), []int{1}
}

func (x *TestResponse) GetTestrsp() string {
	if x != nil {
		return x.Testrsp
	}
	return ""
}

// 请求结构
type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_geecache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_geecache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_geecache_proto_rawDescGZIP(), []int{2}
}

func (x *Request) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Request) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// 响应结构
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_geecache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_geecache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_geecache_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_geecache_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geecache_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_geecache_proto_rawDescGZIP(), []int{4}
}

func (x *SetRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type InvalidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateRequest) Reset() {
	*x = InvalidateRequest{}
	mi := &file_geecache_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateRequest) ProtoMessage() {}

func (x *InvalidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geecache_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateRequest.ProtoReflect.Descriptor instead.
func (*InvalidateRequest) Descriptor() ([]byte, []int) {
	return file_geecache_proto_rawDescGZIP(), []int{5}
}

func (x *InvalidateRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *InvalidateRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_geecache_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_geecache_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_geecache_proto_rawDescGZIP(), []int{6}
}

var File_geecache_proto protoreflect.FileDescriptor

const file_geecache_proto_rawDesc = "" +
	"\n" +
	"\x0egeecache.proto\x12\bgeecache\"'\n" +
	"\vTestRequest\x12\x18\n" +
	"\atestreq\x18\x01 \x01(\tR\atestreq\"(\n" +
	"\fTestResponse\x12\x18\n" +
	"\atestrsp\x18\x01 \x01(\tR\atestrsp\"1\n" +
	"\aRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\" \n" +
	"\bResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"J\n" +
	"\n" +
	"SetRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\";\n" +
	"\x11InvalidateRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\a\n" +
	"\x05Empty2\x94\x02\n" +
	"\fCacheService\x125\n" +
	"\x04Test\x12\x15.geecache.TestRequest\x1a\x16.geecache.TestResponse\x12,\n" +
	"\x03Get\x12\x11.geecache.Request\x1a\x12.geecache.Response\x12,\n" +
	"\x03Set\x12\x14.geecache.SetRequest\x1a\x0f.geecache.Empty\x12:\n" +
	"\n" +
	"Invalidate\x12\x1b.geecache.InvalidateRequest\x1a\x0f.geecache.Empty\x125\n" +
	"\x05Purge\x12\x1b.geecache.InvalidateRequest\x1a\x0f.geecache.EmptyB\x06Z\x04./pbb\x06proto3"

var (
	file_geecache_proto_rawDescOnce sync.Once
	file_geecache_proto_rawDescData []byte
)

func file_geecache_proto_rawDescGZIP() []byte {
	file_geecache_proto_rawDescOnce.Do(func() {
		file_geecache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_geecache_proto_rawDesc), len(file_geecache_proto_rawDesc)))
	})
	return file_geecache_proto_rawDescData
}

var file_geecache_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_geecache_proto_goTypes = []any{
	(*TestRequest)(nil),       // 0: geecache.TestRequest
	(*TestResponse)(nil),      // 1: geecache.TestResponse
	(*Request)(nil),           // 2: geecache.Request
	(*Response)(nil),          // 3: geecache.Response
	(*SetRequest)(nil),        // 4: geecache.SetRequest
	(*InvalidateRequest)(nil), // 5: geecache.InvalidateRequest
	(*Empty)(nil),             // 6: geecache.Empty
}
var file_geecache_proto_depIdxs = []int32{
	0, // 0: geecache.CacheService.Test:input_type -> geecache.TestRequest
	2, // 1: geecache.CacheService.Get:input_type -> geecache.Request
	4, // 2: geecache.CacheService.Set:input_type -> geecache.SetRequest
	5, // 3: geecache.CacheService.Invalidate:input_type -> geecache.InvalidateRequest
	5, // 4: geecache.CacheService.Purge:input_type -> geecache.InvalidateRequest
	1, // 5: geecache.CacheService.Test:output_type -> geecache.TestResponse
	3, // 6: geecache.CacheService.Get:output_type -> geecache.Response
	6, // 7: geecache.CacheService.Set:output_type -> geecache.Empty
	6, // 8: geecache.CacheService.Invalidate:output_type -> geecache.Empty
	6, // 9: geecache.CacheService.Purge:output_type -> geecache.Empty
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_geecache_proto_init() }
func file_geecache_proto_init() {
	if File_geecache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_geecache_proto_rawDesc), len(file_geecache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_geecache_proto_goTypes,
		DependencyIndexes: file_geecache_proto_depIdxs,
		MessageInfos:      file_geecache_proto_msgTypes,
	}.Build()
	File_geecache_proto = out.File
	file_geecache_proto_goTypes = nil
	file_geecache_proto_depIdxs = nil
}
